# Generated by Django 5.2.2 on 2025-10-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0002_alter_task_updateddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='addedDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
